### ISSUE TITLE
Can you host your package on pkg.go.dev?

### ISSUE THREAD

**Issue by piyushdivyankar1994** [richzw/appstore#1]
I spent past few days implementing these functionalities. It is unfortunate that I couldn't find this repository sooner.  If possible you should integrate this into the go-iap package.  https://pkg.go.dev/github.com/awa/go-iap/

**Comment by richzw** [comment]
I will try to add it to https://pkg.go.dev/github.com/awa/go-iap/, however, it seems there is one same PR https://github.com/awa/go-iap/issues/144

**Comment by richzw** [comment]
The new PR https://github.com/awa/go-iap/pull/170 is done

**Comment by richzw** [comment]
@piyushdivyankar1994 , my package could be found here https://pkg.go.dev/github.com/richzw/appstore#section-readme. I will add more docs later.

**Comment by piyushdivyankar1994** [comment]
Let me know if I can help.
