### ISSUE TITLE
question about exported SetRetry func

### ISSUE THREAD

**Issue by holyachon** [richzw/appstore#11]
Hello. Thanks for sharing this great library.

I found that this library may support retry feature(https://github.com/richzw/appstore/commit/17ec239ad869b5493aa0d38c8b0d673fc6dc367a).
It seems that user need to call `SetRetry` for `HTTPClient` in method of `StoreClient`(ex. GetTransactionInfo).
But user can't do that because c.httpCli(HTTPClient) is not exported.

If there's another way I'm not aware of, please let me know.
If not, what do you think about provide some way that allows combining DoFuncs like SetRetry?
Feel free to suggest a better way, or you can modify it, also I'm willing to submit PR for this feature.

**Comment by richzw** [comment]
> It seems that user need to call SetRetry for HTTPClient in method of StoreClient(ex. GetTransactionInfo).
But user can't do that because c.httpCli(HTTPClient) is not exported.

The `c.httpCli` is not exported. Originally, I wanto user could use those funcs like `SetResponseErrorHandler` within `StoreClient`. Maybe something is missing, please correct me.

> If not, what do you think about provide some way that allows combining DoFuncs like SetRetry?
Feel free to suggest a better way, or you can modify it, also I'm willing to submit PR for this feature.

Welcome your PR, we could do some discussion on it about this issue.

@holyachon

**Comment by holyachon** [comment]
@richzw Hi. I made a PR about this issue #12 
Please check it out when you get a chance :)

**Comment by holyachon** [comment]
```
     	c := &appstore.StoreConfig{}
	appstoreClient := appstore.SetRetry(
		client,
		&appstore.JitterBackoff{
			Initial: time.Millisecond * 500,
			Max:     time.Second * 10,
		},
		appstore.ShouldRetryDefault,
	)
        storeClient := appstore.NewStoreClientWithHTTPClient(c, appstoreClient)
```

it works well. I will submit new PR that add this example in README.
Thank you for your quick response! @richzw

**Comment by richzw** [comment]
> ```
>      	c := &appstore.StoreConfig{}
> 	appstoreClient := appstore.SetRetry(
> 		client,
> 		&appstore.JitterBackoff{
> 			Initial: time.Millisecond * 500,
> 			Max:     time.Second * 10,
> 		},
> 		appstore.ShouldRetryDefault,
> 	)
>         storeClient := appstore.NewStoreClientWithHTTPClient(c, appstoreClient)
> ```
> 
> it works well. I will submit new PR that add this example in README. Thank you for your quick response! @richzw

Thank you very much for your detailed response and your PR.
