### ISSUE TITLE
No validation of leaf certificate

### ISSUE THREAD

**Issue by Guillembonet** [richzw/appstore#3]
Hey, I believe that your code is not validating the first certificate in the chain and therefore anyone can send a fake server-to-server notification and get validated. See more details in [the comment I left in stackoverflow](https://stackoverflow.com/a/75821860/12813000).

Happy to provide more info if needed!

**Comment by richzw** [comment]
Yes, you are right. To ensure the integrity of the certificate chain, it is necessary to verify the leaf certificate. I overlooked this point at the time. I could fix it later, or welcome to submit your PR.

**Comment by Guillembonet** [comment]
@richzw okay yeah, leave it for me I will PR later. Always nice to contribute to opensource!
