### ISSUE TITLE
调用history接口分页的时候，有死循环

### ISSUE THREAD

**Issue by tt2lzx** [richzw/appstore#8]
![img_v3_026u_99428068-5ffc-4284-8dd5-b925ac96349g](https://github.com/richzw/appstore/assets/25704107/32273a58-17eb-4682-bec5-db45c104d702)
这里用了一个函数工厂的调用链模式。 但是有两层调用链是在for循环里面的，client生命周期是for循环外部定义的。导致每次循环都会额外追加两层调用链函数。。 请求的分页参数就不对了

**Comment by richzw** [comment]
After refactoring the code, I failed to conduct further testing. I apologize for the oversight. Could you please fix it with one PR? @tt2lzx

**Comment by richzw** [comment]
@tt2lzx , Just fix it in the later release, could you please verify it with the latest release?
